testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51OubhsSAkfFPs5lW1kTN2pCiRh2Yzl43i3hcuiXdtyDzuC38VZVekNJwTIiCRdHQXITJhMDtKm3FFqZlMzkbWHse00GmRSOVYk" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_3cs8xIc0S4Kk9I47ss" #only needed if using Stripe
client_id = "809679568535-a6ea7s217404qoi375d8ghdanm800j7a.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://management-system.streamlit.app/"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee